apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-operator-plugin-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update

- apiGroups:
  - 'admissionregistration.k8s.io'
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - list
  - get
  - update
