kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terraform-operator-plugin-manager
subjects:
- kind: ServiceAccount
  name: terraform-operator-plugin-manager
  namespace: tf-system
roleRef:
  kind: ClusterRole
  name: terraform-operator-plugin-manager
  apiGroup: rbac.authorization.k8s.io
