apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-opeartor-plugin-mutations
data:
  mutations.json: |-
    {
      "monitor": {
        "image": "ghcr.io/galleybytes/monitor:0.1.3",
        "image_pull_policy": "IfNotPresent",
        "escape_key": "tfomanager.galleybytes.com/monitor",
        "config_map_key_map": {
          "CLUSTER_NAME": "kind-kind",
          "MONITOR_MANAGER_SERVICE_HOST": "https://terraform-operator-plugin-manager.tf-system.svc"
        }
      }
    }
