apiVersion: v1
kind: Service
metadata:
  name: terraform-operator-plugin-manager
  namespace: tf-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: terraform-operator-plugin-manager
    component: manager
  sessionAffinity: None
  type: ClusterIP
